//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Import
    {
        public int ImportSEQ { get; set; }
        public string FileName { get; set; }
        public Nullable<byte> ImportType { get; set; }
        public Nullable<System.DateTime> ImportedDate { get; set; }
        public string ImportedBy { get; set; }
    }
}
