//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Allowance
    {
        public System.DateTime ChangeDate { get; set; }
        public byte Currency { get; set; }
        public Nullable<decimal> Bus { get; set; }
        public Nullable<decimal> Train { get; set; }
        public Nullable<decimal> MD { get; set; }
        public Nullable<decimal> Director { get; set; }
        public Nullable<decimal> Manager { get; set; }
        public Nullable<decimal> N1 { get; set; }
        public Nullable<decimal> N2 { get; set; }
        public Nullable<decimal> N3 { get; set; }
        public Nullable<decimal> JpnUniGrade { get; set; }
        public Nullable<decimal> Local1stInterviewer { get; set; }
        public Nullable<decimal> Local2ndInterviewer { get; set; }
        public Nullable<decimal> Overseas1stInterviewer { get; set; }
        public Nullable<decimal> Overseas2ndInterviewer { get; set; }
        public Nullable<decimal> MarketingTeamAllowance { get; set; }
        public Nullable<decimal> MentorAllowance { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    }
}
