//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Holidays
    {
        public int ID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> Holiday_Date { get; set; }
        public string Description { get; set; }
    }
}
