//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Salary
    {
        public byte Currency { get; set; }
        public byte Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
