//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Staff
    {
        public int StaffID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string NRC { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> PermanentDate { get; set; }
        public string BankInformation { get; set; }
        public string PermanentAddress { get; set; }
        public string TemporaryAddress { get; set; }
        public string PhoneNo { get; set; }
        public string EmergencyPhoneNo { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<decimal> UniformCharges { get; set; }
        public Nullable<int> FingerPrintID { get; set; }
        public Nullable<byte> OfficeCD { get; set; }
        public string CompanyCD { get; set; }
        public string DepartmentCD { get; set; }
        public string SubDivisionCD { get; set; }
        public string PositionCD { get; set; }
        public string TransportationCD { get; set; }
        public Nullable<byte> Currency { get; set; }
        public string Photo { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> Effort { get; set; }
        public Nullable<bool> DeleteFlg { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
