//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JSAT_HREntities : DbContext
    {
        public JSAT_HREntities()
            : base("name=JSAT_HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<L_Import> L_Import { get; set; }
        public virtual DbSet<M_Transportation> M_Transportation { get; set; }
        public virtual DbSet<Staff_Allowance> Staff_Allowance { get; set; }
        public virtual DbSet<M_User> M_User { get; set; }
        public virtual DbSet<M_Office> M_Office { get; set; }
        public virtual DbSet<M_Department> M_Department { get; set; }
        public virtual DbSet<M_Company> M_Company { get; set; }
        public virtual DbSet<M_Message> M_Message { get; set; }
        public virtual DbSet<M_Payroll> M_Payroll { get; set; }
        public virtual DbSet<M_Position> M_Position { get; set; }
        public virtual DbSet<M_SubDivision> M_SubDivision { get; set; }
        public virtual DbSet<Payroll_Deduction> Payroll_Deduction { get; set; }
        public virtual DbSet<M_Salary> M_Salary { get; set; }
        public virtual DbSet<L_Log> L_Log { get; set; }
        public virtual DbSet<M_Leave> M_Leave { get; set; }
        public virtual DbSet<M_Attendance> M_Attendance { get; set; }
        public virtual DbSet<M_Staff> M_Staff { get; set; }
        public virtual DbSet<Payroll_Allowance> Payroll_Allowance { get; set; }
        public virtual DbSet<M_Allowance> M_Allowance { get; set; }
    }
}
