//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll_Deduction
    {
        public string StaffID { get; set; }
        public int YYYYMM { get; set; }
        public Nullable<System.TimeSpan> LateTime { get; set; }
        public Nullable<int> HourlyUnpaidLeave { get; set; }
        public Nullable<byte> UnpaidLeave { get; set; }
        public Nullable<decimal> LateTimeFees { get; set; }
        public Nullable<decimal> HourlyUnpaidLeaveFees { get; set; }
        public Nullable<decimal> UnpaidLeaveFees { get; set; }
        public Nullable<decimal> SocialWelfare { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
    }
}
