//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll_Allowance
    {
        public string StaffID { get; set; }
        public int YYYYMM { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> Effort { get; set; }
        public Nullable<decimal> MD { get; set; }
        public Nullable<decimal> Director { get; set; }
        public Nullable<decimal> Manager { get; set; }
        public Nullable<decimal> N1 { get; set; }
        public Nullable<decimal> N2 { get; set; }
        public Nullable<decimal> N3 { get; set; }
        public Nullable<decimal> JpnUNiGradurate { get; set; }
        public Nullable<decimal> Local1stInterviewer { get; set; }
        public Nullable<decimal> Local2dstInterviewer { get; set; }
        public Nullable<decimal> Overseas1stInterviewer { get; set; }
        public Nullable<decimal> Overseas2ndInterviewer { get; set; }
        public Nullable<decimal> MarketingTeam { get; set; }
        public Nullable<decimal> Mentor { get; set; }
    }
}
