//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll_Deduction
    {
        public string StaffID { get; set; }
        public int YYYYMM { get; set; }
        public Nullable<int> LateMinutes { get; set; }
        public Nullable<byte> HourlyLeave { get; set; }
        public Nullable<byte> EarlyOut { get; set; }
        public Nullable<decimal> UnpaidLeave { get; set; }
        public Nullable<decimal> LateTimeFees { get; set; }
        public Nullable<decimal> HourlyLeaveFees { get; set; }
        public Nullable<decimal> EarlyOutFees { get; set; }
        public Nullable<decimal> UnpaidLeaveFees { get; set; }
        public Nullable<decimal> SocialWelfare { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
        public Nullable<decimal> UniformCharges { get; set; }
        public Nullable<decimal> TotalDeduction { get; set; }
        public Nullable<decimal> CutUnpaidLeave { get; set; }
        public Nullable<decimal> CutUnpaidLeaveFees { get; set; }
        public Nullable<decimal> MedicalLeave { get; set; }
        public Nullable<decimal> MaternityLeave { get; set; }
        public Nullable<decimal> MedicalLeaveFees { get; set; }
        public Nullable<decimal> MaternityLeaveFees { get; set; }
        public Nullable<decimal> MedicalLeavePercent { get; set; }
        public Nullable<decimal> MaternityLeavePercent { get; set; }
    }
}
