//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Allowance
    {
        public int StaffID { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public Nullable<bool> MD { get; set; }
        public Nullable<bool> Director { get; set; }
        public Nullable<bool> Manager { get; set; }
        public Nullable<bool> N1 { get; set; }
        public Nullable<bool> N2 { get; set; }
        public Nullable<bool> N3 { get; set; }
        public Nullable<bool> JpnUniGradurate { get; set; }
        public Nullable<bool> Local1stInterviewer { get; set; }
        public Nullable<bool> Local2ndInterviewer { get; set; }
        public Nullable<bool> Overseas1stInterviewer { get; set; }
        public Nullable<bool> Overseas2ndInterviewer { get; set; }
        public Nullable<bool> MarketingTeamAllowance { get; set; }
        public Nullable<bool> MentorAllowance { get; set; }
    }
}
