//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Authorization
    {
        public string UserID { get; set; }
        public string ViewID { get; set; }
        public Nullable<bool> ShowView { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
